sudo: false
cache: bundler
language: ruby
rvm:
- 2.3.1
- 2.2.5
- 2.2.0
- 2.1.10
- 2.1.0
- 2.0.0-p648
- 2.0.0
- ruby
- ruby-head
- jruby-9.1.5.0
- jruby-9.0.5.0
- jruby-head
- rbx-2
- rbx-head
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby
  - rvm: ruby-head
  - rvm: jruby-head
  - rvm: rbx-2
  - rvm: rbx-head
notifications:
  email:
    recipients:
      - secure: Nc40zytQ9fRyuq+cCiupSzV4Xlzg56K4tk+Y9x0b2QkD6q559yTn6w61FnVP24i84PL4m1eyXAI+aRI5KLCp7zLV8d0xQBEILPJRduvG7ompfG9ny1QcqjGyWAH0I1skigxbNX7ynuz5Orfb7gQ9EYFOL5FatqsEVTf9dhI6qiQeUc/GuF9oyE5lyegCU8I9LQ3x9+DwOYj//lc1zbBxwlj0sKvSh5kgPdCD43v+hnwijrIGbhy2zRQXgjjPgeb2nb/DOeC8HOkI8ZVQM5FSoHaFgZO9hy663+zE4Qh8/EDMbD0WNNE9VyrJgy3gQvdGtJsreyaj3INjLJ+FEAb1+KP8yYjz8XX/nWsTjEN0RjA5dW9AIh752oV8Fi+T3NoW2wrCYXttq2SRxB0JJhEm8qcR+gMkMftCLtD4aoTBwCsr/ci/2OGOzTsdmkbKTe3j3FvHBCxhrrmPoDrbKEGaFOdeEJTyWXsXIg47gERd7X+eMVXilkUKn5CRDntg9H2Arm/LeXKn/e2jyEVOOcEUp+CwL3SQdV0TGnfySbzdoCsOQPoKYltKj6sE1Nl78c9J2PkImTF7WtVaRnCvQjYLa+uljJHdnL5pvOuYsEpp7SHuJVQ7gppOhnkecUk0efgsa+8nOqftrma18cna7NKZYp1CJCrUQFxm6ckjVfbPfoI=
    on_success: always
    on_failure: always
  webhooks:
  - https://zapier.com/hooks/catch/2y1h4a/
  slack:
    secure: CQ+rNTyD98rgLqmcvtZlB3lehGMZ0hndLd2Y75pKQopMFAvfAECUmoueTP5k2niIhQFfPvZnjoaId1sueIQwlT9XDoOzYC0sNCKTQyzPS1LFv3+mjf7DOsSNwf60gQUvwo1OpcxTqVSc6OxaiSMQOd1AZ9HN6EcuDIk/KHbQ7ugL9Q1I1397/k3QEcW+xPfDCE0r5nVYmAYGt8UisKSVEiReSu8mppbCrg2I0Lr7iX/o+nrGDDgyFo0H8sszb3aUXprkpaNLsU7EhxZtp6wZbk6s/6Dr8MZ1P3tb7ItQija/V44OH2B43xlZdo463P+AlOnAaJP9xLCZlA70GOxnEcZPI459fCzXwPUES1XKoaDt//NgjcLx9GlodfBz79Sz0S9BAN0DHyZ/Ev+juy3Q1wJrls53T+pUXCTYLVG+lhysCd/+4SKv/9NDuZrwnNPTNPBBjsFB1Ysbx62+VzzhmblpQlH+3tR0n5CaCVTFeZvtjJgemt0yXGcU2b9ut7p7eBc83L/b6lVsEGySkHK/XQYOEaz6Ns06IFi3mDw/KXKJVAie36lQus+bpitaFH2vbmtWbUlshvvizG31PlBtHjjwcZQfLHBd+waAeWKT1KNUdBS9zfBcwcrjpRGwTCtZmSFkqv3z4s9vSPWq1PYfKX/RqghdPHSTIOgdjQmjpYc=
